name: Create Draft Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Cache global npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-changelogen-cache

      - name: Install changelogen
        run: npm install -g changelogen

      - name: Cache Go build artifacts
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Get previous tag
        id: get_tags
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 || git rev-list --max-parents=0 HEAD)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: changelog_generator
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          npx changelogen --from ${{ steps.get_tags.outputs.prev_tag }} --to ${{ github.ref_name }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build, Package & Generate Hashes
        run: |
          BINARY_NAME="cloudflare-cli"
          MAIN_PACKAGE_PATH="."
          mkdir ./dist

          GOOS=linux GOARCH=amd64 go build -o "./dist/${BINARY_NAME}-linux-amd64" $MAIN_PACKAGE_PATH
          GOOS=windows GOARCH=amd64 go build -o "./dist/${BINARY_NAME}-windows-amd64.exe" $MAIN_PACKAGE_PATH
          GOOS=darwin GOARCH=amd64 go build -o "./dist/${BINARY_NAME}-darwin-amd64" $MAIN_PACKAGE_PATH
          
          cd ./dist
          zip "${BINARY_NAME}-linux-amd64.zip" "${BINARY_NAME}-linux-amd64"
          zip "${BINARY_NAME}-windows-amd64.zip" "${BINARY_NAME}-windows-amd64.exe"
          zip "${BINARY_NAME}-darwin-amd64.zip" "${BINARY_NAME}-darwin-amd64"
          
          sha256sum * > checksums.txt
          cd ..

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog_generator.outputs.notes }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: ./dist/*